Repository Frame-in-Puzzle/Puzzle-Front, pull requests merged in 2022-02, with the labels that each got.

#24 profileheader 퍼블리싱
  src/Assets/ProfileImg.tsx
  src/Assets/index.ts
  src/Components/ProfileHeader/ProfileHeader.stories.tsx
  src/Components/ProfileHeader/ProfileHeader.tsx
  src/Components/ProfileHeader/Style.ts
Labels: enhancement, JeongDaeWoo

#25 Feature/publishing/profile
  src/Assets/Edit.tsx
  src/Assets/index.ts
  src/Components/Common/Input/Input.stories.tsx
  src/Components/Common/Input/Input.tsx
  src/Components/Common/Input/Style.ts
  src/Components/Common/ToggleButton/Style.ts
  src/Components/Common/ToggleButton/ToggleButton.stories.tsx
  src/Components/Common/ToggleButton/ToggleButton.tsx
  src/Components/PostItem/PostItem.stories.tsx
  src/Components/Profile/ProfileHeader/ProfileHeader.stories.tsx
  src/Components/Profile/ProfileHeader/ProfileHeader.tsx
  src/Components/Profile/ProfileHeader/Style.ts
  src/Components/Profile/ProfileInfo/ProfileInfo.stories.tsx
  src/Components/Profile/ProfileInfo/ProfileInfo.tsx
  src/Components/Profile/ProfileInfo/Style.ts
  src/Components/Profile/ProfileSelectBox/ProfileSelectBox.stories.tsx
  src/Components/Profile/ProfileSelectBox/ProfileSelectBox.tsx
  src/Components/Profile/ProfileSelectBox/Style.ts
Labels: enhancement, JeongTaeHwan

#26 Feature/publishing/button
  src/Components/Button/Button.stories.tsx
  src/Components/Button/Button.tsx
  src/Components/Button/Style.ts
  src/Styles/theme.ts
Labels: enhancement, ImChangGyu

#27 Feature/publishing/profile page
  src/App.tsx
  src/Assets/Edit.tsx
  src/Components/Post/Style.ts
  src/Components/Profile/ProfileHeader/Style.ts
  src/Components/Profile/ProfileInfo/Style.ts
  src/Components/Profile/ProfileSelectBox/ProfileSelectBox.tsx
  src/Components/Profile/ProfileSelectBox/Style.ts
  src/Pages/Profilepage/Profilepage.tsx
  src/Pages/Profilepage/Style.ts
Labels: enhancement, JeongTaeHwan

#30 Feature/publishing/writing items
  .pnp.cjs
  .yarn/cache/@mapbox-hast-util-table-cell-style-npm-0.2.0-92bf5dc7bf-4b05edda2b.zip
  .yarn/cache/mdast-util-from-markdown-npm-0.8.5-0b8b6dc7ba-5a9d0d753a.zip
  .yarn/cache/mdast-util-to-hast-npm-10.2.0-a2f4409b10-72df2dd9bf.zip
  .yarn/cache/mdast-util-to-string-npm-2.0.0-3a5d9c4970-0b2113ada1.zip
  .yarn/cache/micromark-npm-2.11.4-f7ec94840a-f8a5477d39.zip
  .yarn/cache/react-remark-npm-2.1.0-e058fa7342-96d7e221f1.zip
  .yarn/cache/rehype-react-npm-6.2.1-ad8cf4b651-7f16a2cfc3.zip
  .yarn/cache/remark-parse-npm-9.0.0-da1fe74019-5010488054.zip
  .yarn/cache/remark-rehype-npm-8.1.0-08fbf1ebaf-e1152464cf.zip
  .yarn/cache/unified-npm-9.2.2-65676eec78-7c24461be7.zip
  .yarn/cache/unist-util-is-npm-3.0.0-1816040586-d24a5dd80c.zip
  .yarn/cache/unist-util-visit-npm-1.4.1-fdb79796c9-e9395205b6.zip
  .yarn/cache/unist-util-visit-parents-npm-2.1.2-154aede9d7-048edbb590.zip
  package.json
  src/Assets/MarkdownBold.tsx
  src/Assets/MarkdownCode.tsx
  src/Assets/MarkdownHeader.tsx
  src/Assets/MarkdownItalic.tsx
  src/Assets/MarkdownList.tsx
  src/Assets/MarkdownNumberList.tsx
  src/Assets/MarkdownURL.tsx
  src/Assets/MarkdownVerified.tsx
  src/Assets/index.ts
  src/Components/Button/Button.stories.tsx
  src/Components/Button/Button.tsx
  src/Components/Button/Style.ts
  src/Components/Common/Input/Input.stories.tsx
  src/Components/Common/Input/Input.tsx
  src/Components/Common/Input/Style.ts
  src/Components/Input/Input.stories.tsx
  src/Components/Input/Input.tsx
  src/Components/Input/Style.ts
  src/Components/Write/WriteSelectItem/Style.ts
  src/Components/Write/WriteSelectItem/WriteSelectItem.stories.tsx
  src/Components/Write/WriteSelectItem/WriteSelectItem.tsx
  src/Components/Write/WriteTextInput/Style.ts
  src/Components/Write/WriteTextInput/WriteTextInput.stories.tsx
  src/Components/Write/WriteTextInput/WriteTextInput.tsx
  yarn.lock
Labels: enhancement, JeongTaeHwan

#32 DropDown Publishing
  .pnp.cjs
  .storybook/preview.js
  .yarn/cache/hamt_plus-npm-1.0.2-67a52ee1df-af26ea32db.zip
  .yarn/cache/recoil-npm-0.6.1-12c4d62952-823c098e30.zip
  package.json
  src/App.tsx
  src/Atoms/AtomContainer.ts
  src/Atoms/index.ts
  src/Components/DropDown/DropDown.stories.tsx
  src/Components/DropDown/DropDown.tsx
  src/Components/DropDown/Style.ts
  src/Components/DropDownList/DropDownList.tsx
  src/Components/DropDownList/Style.ts
  src/Components/index.ts
  yarn.lock
Labels: enhancement, ImChangGyu

#33 Feature/publishing/dropdown
  src/Components/Common/Header/Header.stories.tsx
  src/Components/Common/Header/Header.tsx
  src/Components/Common/Header/Style.ts
  src/Pages/Mainpage/Mainpage.tsx
  src/Pages/ProfileCheckPage/ProfileCheckPage.tsx
  src/Pages/Profilepage/Profilepage.tsx
Labels: enhancement, ImChangGyu

#35 게시글 상세 조회 퍼블리싱
  src/App.tsx
  src/Assets/BurgerMenu.tsx
  src/Assets/index.ts
  src/Components/ApplyItem/ApplyItem.stories.tsx
  src/Components/ApplyItem/ApplyItem.tsx
  src/Components/ApplyItem/Style.ts
  src/Components/Button/Button.stories.tsx
  src/Components/Button/Button.tsx
  src/Components/Button/Style.ts
  src/Components/DropDownList/DropDownList.stories.tsx
  src/Components/DropDownList/DropDownList.tsx
  src/Components/DropDownList/Style.ts
  src/Components/Tags/TagItem/Style.ts
  src/Components/Tags/TagItem/TagItem.stories.tsx
  src/Components/Tags/TagItem/TagItem.tsx
  src/Components/index.ts
  src/Pages/DetailPage/DetailPage.tsx
  src/Pages/index.ts
  src/Templates/Detail/DetailApply/DetailApply.stories.tsx
  src/Templates/Detail/DetailApply/DetailApply.tsx
  src/Templates/Detail/DetailApply/Style.ts
  src/Templates/Detail/DetailContent/DetailContent.stories.tsx
  src/Templates/Detail/DetailContent/DetailContent.tsx
  src/Templates/Detail/DetailContent/Style.ts
  src/Templates/Detail/DetailTitle/DetailTitle.stories.tsx
  src/Templates/Detail/DetailTitle/DetailTitle.tsx
  src/Templates/Detail/DetailTitle/Style.ts
  src/Templates/Detail/DetailWriter/DetailWriter.stories.tsx
  src/Templates/Detail/DetailWriter/DetailWriter.tsx
  src/Templates/Detail/DetailWriter/Style.ts
  src/Templates/index.ts
Labels: enhancement, ImChangGyu

#36 API 세팅
  .gitignore
  .pnp.cjs
  .yarn/cache/axios-npm-0.26.0-ae9d5291c9-d7a8b898f4.zip
  .yarn/cache/follow-redirects-npm-1.14.9-522f191631-f5982e0eb4.zip
  .yarn/cache/swr-npm-1.2.2-90e14a1b98-723747c7c2.zip
  package.json
  src/Lib/.gitkeep
  src/Lib/Api/apiClient.ts
  yarn.lock
Labels: ImChangGyu, setting
