Repository Frame-in-Puzzle/Puzzle-Front, pull requests merged in 2022-01, with the labels that each got.

#4 Add : Folder 세팅
  src/Assets/.gitkeep
  src/Components/.gitkeep
  src/Hooks/.gitkeep
  src/Pages/.gitkeep
  src/Styles/.gitkeep
  src/Utils/.gitkeep
Labels: ImChangGyu, setting

#5 react18 로 버전업
  .pnp.cjs
  .yarn/cache/react-dom-npm-17.0.2-f551215af1-1c1eaa3bca.zip
  .yarn/cache/react-dom-npm-18.0.0-rc.0-ca8a99e25f-713db349fa.zip
  .yarn/cache/react-npm-17.0.2-99ba37d931-b254cc17ce.zip
  .yarn/cache/react-npm-18.0.0-rc.0-5159bcba02-bb886ab411.zip
  .yarn/cache/scheduler-npm-0.20.2-90beaecfba-c4b35cf967.zip
  .yarn/cache/scheduler-npm-0.21.0-rc.0-next-fe905f152-20220107-d3c5c28573-72d1e7451c.zip
  package.json
  yarn.lock
Labels: ImChangGyu, setting

#6 각종 template 세팅
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/delete-merged-branch-config.yml
Labels: ImChangGyu, setting

#12 Feature/setting/absolutepath
  src/App.tsx
  tsconfig.json
Labels: ImChangGyu, setting

#11 Feature/setting/theme
  src/App.tsx
  src/Styles/theme.ts
Labels: JeongTaeHwan, setting

#13 Globalfont 설정
  src/App.test.tsx
  src/Fonts/Poppins-Black.ttf
  src/Fonts/Poppins-BlackItalic.ttf
  src/Fonts/Poppins-Bold.ttf
  src/Fonts/Poppins-BoldItalic.ttf
  src/Fonts/Poppins-ExtraBold.ttf
  src/Fonts/Poppins-ExtraBoldItalic.ttf
  src/Fonts/Poppins-ExtraLight.ttf
  src/Fonts/Poppins-ExtraLightItalic.ttf
  src/Fonts/Poppins-Italic.ttf
  src/Fonts/Poppins-Light.ttf
  src/Fonts/Poppins-LightItalic.ttf
  src/Fonts/Poppins-Medium.ttf
  src/Fonts/Poppins-MediumItalic.ttf
  src/Fonts/Poppins-Regular.ttf
  src/Fonts/Poppins-SemiBold.ttf
  src/Fonts/Poppins-SemiBoldItalic.ttf
  src/Fonts/Poppins-Thin.ttf
  src/Fonts/Poppins-ThinItalic.ttf
  src/Styles/GlobalStyle.ts
  src/index.css
  src/index.tsx
Labels: bug, JeongDaeWoo, setting

#14 react-router 빠진 부분 추가
  src/App.tsx
  src/Components/index.ts
  src/Pages/index.ts
  tsconfig.json
Labels: ImChangGyu, fix

#15 font
  src/Components/index.ts
  src/Pages/index.ts
  src/index.css
  src/index.tsx
Labels: JeongDaeWoo, fix

#17 Header 퍼블리싱
  .storybook/main.js
  .storybook/preview.js
  src/Assets/DownArrow.tsx
  src/Assets/PuzzleLogo.tsx
  src/Assets/index.ts
  src/Components/Common/Header/Header.stories.tsx
  src/Components/Common/Header/Header.tsx
  src/Components/Common/Header/Style.ts
  src/Components/index.ts
  src/Styles/GlobalStyle.ts
  src/Styles/emotion.d.ts
  src/Styles/theme.ts
Labels: enhancement, ImChangGyu, Code-Review

#18 Add : Banner 컴포넌트 추가
  src/Assets/BannerImg.tsx
  src/Assets/index.ts
  src/Components/Common/Banner/Banner.stories.tsx
  src/Components/Common/Banner/Banner.tsx
  src/Components/Common/Banner/Style.ts
Labels: enhancement, JeongTaeHwan

#20 Update : Fix Puzzle Logo
  src/Assets/PuzzleLogo.tsx
Labels: ImChangGyu, fix

#19 Add : ActiveItem Components 추가
  src/Assets/PostItemImg.tsx
  src/Assets/index.ts
  src/Components/Common/PostItem/PostItem.stories.tsx
  src/Components/Common/PostItem/PostItem.tsx
  src/Components/Common/PostItem/Style.ts
Labels: enhancement, JeongTaeHwan, Code-Review

#22 Add : MainPage 퍼블리싱
  src/App.tsx
  src/Assets/PostItemImg.tsx
  src/Components/Common/Banner/Style.ts
  src/Components/Common/PostItem/PostItem.tsx
  src/Components/Post/Post.stories.tsx
  src/Components/Post/Post.tsx
  src/Components/Post/Style.ts
  src/Components/PostItem/PostItem.stories.tsx
  src/Components/PostItem/PostItem.tsx
  src/Components/PostItem/Style.ts
  src/Pages/Mainpage/Mainpage.tsx
Labels: enhancement, JeongTaeHwan
