Repository Frame-in-Puzzle/Puzzle-Front, pull requests merged in 2022-06, with the labels that each got.

#85 게시글 등록 로직 추가 및 툴바 수정, Preview 수정
  src/App.tsx
  src/Components/Write/Style.ts
  src/Components/Write/WriteTextForm.tsx
  src/Lib/Api/post/post.ts
  src/Lib/Data/List.ts
Labels: enhancement, JeongTaeHwan, fix

#87 Preview Modal 퍼블리싱
  src/Atoms/AtomContainer.ts
  src/Atoms/index.ts
  src/Components/Write/Modal/PreviewModal.stories.tsx
  src/Components/Write/Modal/PreviewModal.tsx
  src/Components/Write/Modal/Style.ts
  src/Components/Write/WriteTextForm.tsx
Labels: enhancement, JeongTaeHwan

#94 Feature/infinitelogin
  src/Atoms/AtomContainer.ts
  src/Atoms/index.ts
  src/Components/Common/Header/Header.tsx
  src/Components/Common/HeaderItem/HeaderItem.tsx
  src/Components/Common/HeaderNotLoginItem/HeaderNotLoginItem.tsx
  src/Components/Profile/ProfileHeader/ProfileHeader.tsx
  src/Components/SignUp/SignUpForm/SignUpForm.tsx
  src/Pages/DetailPage/DetailPage.tsx
  src/Pages/Mainpage/Mainpage.tsx
  src/Pages/ProfileCheckPage/ProfileCheckPage.tsx
  src/Pages/Profilepage/Profilepage.tsx
  src/Pages/PromotionPage/PromotionPage.tsx
Labels: enhancement, JeongDaeWoo, fix

#95 게시글 수정 기능 구현
  .pnp.cjs
  .yarn/cache/filter-obj-npm-1.1.0-84128fc26d-cf2104a7c4.zip
  .yarn/cache/query-string-npm-7.1.1-55c6f31f52-b227d1f588.zip
  .yarn/cache/split-on-first-npm-1.1.0-e2f3ab5e4e-16ff85b54d.zip
  .yarn/cache/strict-uri-encode-npm-2.0.0-1ec3189376-eaac4cf978.zip
  package.json
  src/Components/Tags/TagModal/TagModal.tsx
  src/Components/Write/WriteTextForm.tsx
  src/Lib/Api/post/post.ts
  src/Lib/Data/List.ts
  src/Templates/Detail/DetailTitle/DetailTitle.tsx
  yarn.lock
Labels: bug, enhancement, ImChangGyu

#100 Feature/add default image
  src/Assets/DefaultImage.tsx
  src/Assets/index.ts
  src/Components/MyPost/MyPost.tsx
  src/Components/MyPostItem/MyPostItem.tsx
  src/Components/PostItem/PostItem.tsx
  src/Components/Write/WriteTextForm.tsx
Labels: enhancement, JeongTaeHwan, fix
